# @baseUrl = localhost:8080
# @baseUrl = {{$processEnv REPLAY_ENGINE_PUB_IP}}

@baseUrl = 167.172.54.38:8080

### Ping
POST http://{{baseUrl}}/ping

### Pause
POST http://{{baseUrl}}/simulation/pause

### Resume
POST http://{{baseUrl}}/simulation/resume

### Restart
POST http://{{baseUrl}}/simulation/restart

# Symbol Hydration

### AMD
POST http://{{baseUrl}}/control/hydrate
Content-Type: application/json

{
    "symbol": "AMD",
    "date": "2025-03-20"
}

### NVDA

POST http://{{baseUrl}}/control/hydrate
Content-Type: application/json

{
    "symbol": "QQQ" ,
    "date": "2025-03-20"
}

### GET Settings

GET http://{{baseUrl}}/control/settings


### POST (Set) Settings 1.0 timescale
POST http://{{baseUrl}}/control/settings
Content-Type: application/json

{
    "timescale": 1,
    "simulation-date": "2025-03-20"
}


### POST (Set) Settings 2.0 timescale
POST http://{{baseUrl}}/control/settings
Content-Type: application/json

{
    "timescale": 3600.0,
    "simulation-date": "2025-03-20"
}

### 
POST http://{{baseUrl}}/control/settings
Content-Type: application/json

{
    "timescale": 60.0,
    "simulation-date": "2025-03-20"
}